version: '2'
services:

  people-app:
    image: infrastructure_homework
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      -   db
    environment:
      JAVA_OPTS: "-Xms1024m -Xmx1024m"
      DATABASE_URL: jdbc:postgresql://db/postgres

  db:
    image: postgres
    hostname: db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
