name: Deploy container to Amazon ECR

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: test_app
        run: |
          IMAGE_TAG=$(./gradlew properties --no-daemon --console=plain -q | grep "^version:" | awk '{printf $NF}')
          make docker-push BUILD_TYPE=prod AWS_REPO=$ECR_REGISTRY/$ECR_REPOSITORY IMG_TAG=$IMAGE_TAG

      - name: Force deployment to Amazon ECS
        run: |
          make aws-force-deploy
