build:
  maxIssues: 0
  excludeCorrectable: false

complexity:
  LongParameterList:
    active: true
    functionThreshold: 130
    constructorThreshold: 130

exceptions:
  SwallowedException:
    active: false

naming:
  FunctionMaxLength:
    active: true
    maximumFunctionNameLength: 30

style:
  NewLineAtEndOfFile:
    active: false
  ReturnCount:
    active: true
    max: 3


performance:
  SpreadOperator:
    active: false





