config:
  validation: true
  warningsAsErrors: true

build:
  maxIssues: 0

complexity:
  LongParameterList:
    functionThreshold: 12
    constructorThreshold: 12
    ignoreDefaultParameters: true

style:
  NewLineAtEndOfFile:
    active: false

performance:
  SpreadOperator:
    active: false





